### ISSUE TITLE
新版RAP v0.13需求整理/开发进度/意见反馈帖

### ISSUE THREAD

**Issue by Bosn** [thx/RAP#105]
v0.12需求已定稿，新需求将纳入到下一个版本v0.13。特殊紧急需求视情况而定。

### v0.12 需求及开发进度

    以下为v0.12需求列表，后缀为实现优先级，数字越**小**优先级越高。
    暂时开发、维护只有楼主一人... 而且只有0.1人力（T . T）大都为周末业余时间搞，进度慢见谅。
    欢迎开源爱好者共同优化RAP。

* 稳定性升级
    * [x] 备份更加智能（1）
    * [x] 增加草稿箱功能，未提交的数据关闭浏览器重开后保存在本地存储中。（1）
* Open API升级
    * [x] 实现对Mock规则的API访问与管理 (2) 2015/7/21 #153 
    * [x] 自动运行脚本用的接口数据校验逻辑服务(2) 2015/7/21 #163 
    * [x] 开放API梳理，增加JSON格式接口（2)
    * [x] RAP插件白名单曝光 #117
    * [x] 将projectDataOriginal以jsonp形式提供给外部使用 #132
* 安全升级 
    * [x] 团队管理、团队列表（1）#210 
    * [x] 访问权限、可见性（1） #210 
    * [ ] 平台用户管理（3）#210 
    * [x] struts更新（1） #201 
* 用户体验、功能升级
    * [ ] 接口描述支持Markdown语法，取代@code @end语法高亮 （3）#123
    * [ ] 完善自定义函数在描述中的显示 （3）
    * [ ] 将@mock与正常备注做拆分（3）
    * [ ] 完成个人设置页面、消息通知机制。（3）
    * [x] 在定义接口的位置就可以快速查看JSON格式（通过MOCK服务）（1）
    * [ ] 支持批量转移（4）#145
    * [ ] 版本修改对比（4）
    * [ ] 页面/请求排序 （4）
    * [ ] 一个接口不同状态（正常、错误等情况）的处理 （3）
    * [ ] 直接在RAP接口文档编辑的位置就能查看Mock数据，不用再跳到控制台。(3)
    * [ ] MockJS可视化JSON结构编辑切换及同步 (3)
    * [x] 功能升级-增加虚拟根节点，更方便的控制根级最外层结构的规则（2）
    * [ ] 权限管理-增加项目对非成员是否开放的控制（2）
    * [ ] 左侧导航过长时的用户体验优化（3）
    * [ ] 文档导出的优化（3）
    * [x] Tab 切换添加路由 （3）#129
    * [ ] 接口列表里面希望可以添加一个排序功能 #173 
* 插件、Mock升级
    * [x] 支持request method （4）
    * [ ] 支持promise（2）
    * [ ] 支持RequireJS (2) #116 
    * [x] 支持对console.log输出格式的控制（2） #157 
    * [x] 支持HTTP Method校验 #140 
    * [x] RAP插件支持其它插件需要重构提供基本接口 #124
* 优化部署方式
    * [ ] 使用Maven管理依赖包 （4）#201
    * [ ] 外网部署的单元测试数据写入（4）
    * [ ] 引导式安装、配置MySQL、检查版本、收集管理员信息等（3）
* 自动测试升级
    * [ ] pageTester测试页面，采取Java服务端发送请求以解决跨域问题。可考虑nginx反向代理的方案解决跨域问题。Session/cookie问题还在调研。（3）
* 其它
    * [ ] 撰写开发者手册，帮助开源爱好者了解RAP，并加入RAP的开发行列中 （2）
    * [x] 更新用户手册（1）#170
* BUG修复
    * [ ] 在“备注”那一栏，如果字数多的话，会有一部分隐藏掉，应该是属性overflow-x: hidden;问题
    * [x] Mock数据中文乱码问题 #158 
    * [x] 在object嵌套的时候参数化功能会失效 #152 
    * [x] RESTFul Path /zoo/:id/view/:id 无法正确解析 #130 
    * [x] 发现如果url中出现多个REST参数时报错 #119
    * [x] Object级参数的@mock=function不覆盖子结构 #108
    * [x] rap设置的数据类型和实际返回的不同 #110
    * [x] 模块名过长导致报错 #111
    * [x] 发现如果url中出现多个REST参数时报错 #119
    * [x] JSON数据导入BUG #131
    * [x] 数据统计的数据库更新[定时任务]  #121 
### 开发分支
目前就是用master分支，稳定后会合入release

### RAP v0.13计划中的需求
* 自动化测试方向的功能、合作(TanxU, IF-TEST)
    * 加强后端和前端的边界校验
        * RAP插件根据设定，自动生成边界数据，如带有注入的HTML文本、超长文本、空文本等等。
        * 增加CASE管理，将Mock数据、CASE Mock数据、备注分离。
* 国际化
    * 引入Dredd、Aglio等工具
    * 继续与Blueprint API打通
* 用户体验优化
    * Blueprint API文本编辑切换及同步 (待定)
    * 项目级锁定，改为git提交类似的冲突管理，不再锁定实时项目。{改动较大}
* 外网部署优化
    * 对外部署RAP时的contextRoot配置 #106

**Comment by channingZhou** [comment]
导出word功能： 导出来的word是这样：
![p1](https://cloud.githubusercontent.com/assets/11330083/6613090/9a80f55a-c8c2-11e4-93d9-0bd7bc5f0798.png)
Description 、Request Param List 这些可以改成中文吗？ 并且不让它们出现在左边的导航栏里面。

**Comment by nunnly** [comment]
接口详情页面，右侧可以滚动起来，左侧列表过长的时候，必须点击了，再滚到顶部

**Comment by cctestss** [comment]
1 增加接口的版本管理，同一个接口不同的版本有不同的参数和结果
2 同一个接口同一个版本 返回不同结果如返回200和返回500时的结构不一样，但是在编辑mock规则中不好编辑

**Comment by Bosn** [comment]
@nunnly 这个问题我也发现了，会加到下个版本需求中过去。
@cctestss 
问题1-导出文档：
    导出文档会按照亲说的优化的，另外也会提供多种导出/查看文档的方式（已实现，完善中）。

问题2-接口版本管理：
    亲可以描述你的使用场景么？如果固定一个版本返回接口数据，接口就不同步了。接口复制功能也提供了。如果任意版本均可返回MOCK数据，在性能上会有较大的影响。我需要一个能够说服我实现这个需求的强理由。

问题3-同一接口200/500
    RAP文档中的接口，只是一个抽象层级，其实更确切的说，RAP最小的单元是“接口结构”，例如亲的接口是：500/200名字叫获取用户数据，可以创建两个接口：获取用户数据500/获取用户数据200。从实际应用上看，前者往往模块级或项目级通用，更没有必要混在每一个接口的定义里。

**Comment by wonderffee** [comment]
刚开始用RAP，很好用，其实我更主要是把它当写接口文档工具用的，更喜欢它的自动导入JSON变返回参数列表的功能，而不是用它来生成测试数据，可能大公司更需要这个，当然我们可能以后也会用到这个。
我所在的是小公司，之前基本没有接口文档，接口什么的都靠QQ传达，什么返回参数都是靠抓包，有了RAP自动导入JSON功能，整理接口就很方便啦，非常感谢RAP这个工具。
说几个刚刚接触RAP的小问题，可能也算需求吧：
1、一个接口的请求参数好像要一个一个输入，能不能像导入JSON自动生成JSON列表一样，导入一个抓包得到的请求链接（比如GET请求，不是JSON的）就可以就可以生成请求参数列表？
2、每个接口页面的顶部都是大号字体的“接口详情”，我觉得是不是更适合修改为大号字体的接口具体名称？感觉不好看当前的接口是哪个接口，左侧的列表里面也不容易看，改成红色背景高亮可能更好一点吧。
3、创建新模块从右到左感觉不太习惯，如果模块太多担心顶部放不下的问题

**Comment by GrayLuo** [comment]
HI,各位，首先感觉各位无私的贡献，我们团队在使用RAP的过程中有时候会添加很多描述说明，而且有一定的格式，所以希望能够支持Markdown。
其中这个问题来源于如何在某个接口参数中描述多个错误码和相关信息。比如
{"response":{"code":1,"msg":"权限受限"}}
我要描述code的几种错误码分别是什么，我不知道在哪里添加为好，类似于这种枚举。

**Comment by Bosn** [comment]
这个可以有

**Comment by interchen** [comment]
希望可以在接口定义的界面上查看json格式的响应数据

**Comment by Bosn** [comment]
嗯，好想法，采纳

**Comment by interchen** [comment]
使用json导入响应数据时，下一次修改再点击导入json数据时，输入框是空白的，希望可以把当前的响应数据以json格式初始化在输入框中，便于做小调整

**Comment by Bosn** [comment]
@interchen 导入JSON数据和文档数据是不等价的，
JSON数据只包含基本的数据结构，并不包含字段含义、字段备注、MOCK数据等等信息。

JSON导入的原意是增量导入，并不是全量替换。


如果你有更好的建议，请考虑以上细节给出方案，谢谢。

**Comment by interchen** [comment]
新的建议
{
"key": "这是mock数据" //如果这个注释可以被直接解析到描述那栏就太棒了
}
我习惯在Sublime里编写API返回值，如果在value后面可以直接写注释，且这个注释可以直接被解析到描述那栏就太方便了

**Comment by Bosn** [comment]
@interchen 你说的这个其实就是主帖**计划中需求**的：
```
用户体验优化
MockJS可视化JSON结构编辑切换及同步 (待定)
```
部分，这块儿需要很多细节，需要定义注释的格式如何与文档结构相互转换。涉及到的开发量也比较大。
这块儿我再想想吧。

**Comment by interchen** [comment]
@Bosn 理解！这是在使用过程中感受最深的，因为导入完json后，还要一个个地去写描述确实是比较麻烦

**Comment by Bosn** [comment]
@interchen 描述是可以留空的。。。而且就算提供了JSON格式的，写在JSON注释里和写在GUI的格子里，其实代价是一样的....

另外GUI工具后续也会做更多优化，比如自动提示、智能补全，其实JSON主要是为了方便大家编辑数据的基本结构，其它操作还是要在GUI工具里完善。

**Comment by KevinOfNeu** [comment]
是否可以用Node起一个server？前后端尽量打通，甚至共享一些数据模型。

**Comment by Bosn** [comment]
@KevinOfNeu RAP是J2EE做的，暂时不支持Node。
欢迎各位开源爱好者使用Node重构RAP。

**Comment by colincatsu** [comment]
1自动化测试接口功能
2，版本修改比对，直接可以查看修改的字段

**Comment by Bosn** [comment]
v0.12.0需求列表定稿！！！
时间预计10月前....

如果加快时间？？？
请看原帖....

感谢您的使用，再见！！！

**Comment by Chener** [comment]
一个小需求：

能不能将【编辑项目】改为【编辑项目下的某模块】。只要有一个人在编辑，整个项目就锁定，其他人不能编辑的感觉真蛋疼啊楼主。多开几个项目的话，每次还要统一版本号，有点蛋疼。

**Comment by Bosn** [comment]
@Chener 最开始做了很复杂的版本管理解决冲突问题。。。。后来发现实际应用中，并不是很常见一大堆人非要同一时间编辑同一个项目。。。。。

如果你真有这个需求，其实是可以建立不同项目的（根据版本/模块拆分），然后通过**项目路由**的功能将MOCK数据关联起来。

具体见视频教程[http://thx.github.io/RAP/study.html](http://thx.github.io/RAP/study.html) 中的**项目间共享数据**小节有详细的讲解。

**Comment by Chener** [comment]
@Bosn 原来项目路由就是干这个的啊。

现在就是这么做的，那个视屏教程之前过了2遍。但就像我上面说的，每次完成一个版本开发还要统一搞下版本号，略微蛋疼。而且，项目多了后满屏幕的项目看起来也找不到北。

再者，也不需要解决版本管理冲突问题的吧，一切和之前一样，只不过现在以项目内模块作为编辑状态进入的单元，锁定的也只是项目内模块。一旦保存或者新增模块，按保存事件递增版本号就好啦（慢存的话加个提示之类的帮助解决版本号问题）。

**Comment by Bosn** [comment]
### 对于问题一：版本问题
对于版本问题，直接修改接口就好了，在提交时使用普通的保存，而不要用快速保存，有版本号的设置。
这样再以后想查看老版本时，在版本管理界面查看对应版本（和注释）即可查看甚至切换回旧的版本。

RAP主要是提供各种查看、组织形式，具体怎么组织还是要看自己。如果你有更好的解决方案，可以给一些具体的方案，如果好，我也可以考虑加到后续需求里。


### 对于问题二：冲突解决问题
模块级锁定我也想过，但是目前整个工作区的工作模式，是以整个项目作为数据单元传输的，改为模块级成本较大，也存在很多模块的同步问题。所以开发量较大，但实际要同时编辑相同模块的情况其实并不多。这块儿需求我再考虑下。

**Comment by Bosn** [comment]
@Chener 

### 对于问题一：版本问题
对于版本问题，直接修改接口就好了，在提交时使用普通的保存，而不要用快速保存，有版本号的设置。
这样再以后想查看老版本时，在版本管理界面查看对应版本（和注释）即可查看甚至切换回旧的版本。

RAP主要是提供各种查看、组织形式，具体怎么组织还是要看自己。如果你有更好的解决方案，可以给一些具体的方案，如果好，我也可以考虑加到后续需求里。


### 对于问题二：冲突解决问题
模块级锁定我也想过，但是目前整个工作区的工作模式，是以整个项目作为数据单元传输的，改为模块级成本较大，也存在很多模块的同步问题。所以开发量较大，但实际要同时编辑相同模块的情况其实并不多。这块儿需求我再考虑下。

**Comment by Chener** [comment]
@Bosn 改动成本是挺大的。

那能不能把主页上项目显示增加个类似文件夹的功能，及可创建文件夹，文件夹里可放多个项目，这样项目一多就不会觉得乱了~~

**Comment by Bosn** [comment]
@Chener 有的啊，就是分组功能啊！在上面选择团队，然后就可以按照业务线、分组去分类自己的项目咯~~~

具体的分组页面，添下收藏夹吧。

**Comment by Chener** [comment]
@Bosn good idea 啊，我一直误以为分组分的是团队成员的组。。。

**Comment by Chener** [comment]
@Bosn 额，我又来了。

页面及页面下接口添加后能在编辑状态下改变其排序么？在一段时间的修修改改后，发现顺序有段乱，强迫症表示心里好堵。

和这条需求有点关系：“ 左侧导航过长时的用户体验优化”。

**Comment by Bosn** [comment]
@Chener 

暂时没有排序功能，现以字母顺序为展示顺序。
排序设计到UI较大改动，且收益很小。在v0.12的众多需求比，这个需求意义不大。
亲感兴趣可以自己去实现这个功能。

**Comment by Chener** [comment]
@Bosn 

好的，但现在字母顺序排序好像也不行啊。
![default](https://cloud.githubusercontent.com/assets/4148928/7806414/1ed5ac8a-03b3-11e5-94ce-1c5a75b1f5cd.png)
特地在汉字前面加了 abc，结果还是没有改变顺序，完全就是添加时的顺序，我遗漏了什么么？

**Comment by Bosn** [comment]
@Chener 

额。。。我说的字母顺序是参数列表里的顺序。不是模块下页面/请求的顺序。
页面/请求排序也可以做，我记录下。

**Comment by Chener** [comment]
@Bosn 

好的~鼓掌~

**Comment by Steven-Zhu** [comment]
非常期待依赖包管理Maven的加入

**Comment by Bosn** [comment]
需求征集暂时关闭...

**Comment by Bosn** [comment]
开发状态更新，v0.12正在码... 大家有需求随时调整，后进需求规划到v0.13里。

v0.12里的需求有感兴趣想要帮做的，欢迎提交MR。感激不尽。

**Comment by nunnly** [comment]
查看和编辑接口的页面，左侧的列表，是不是应该添加一个全部收起和全部展开的功能？

**Comment by Maktub714** [comment]
在toolbox.xml配置文件里，是不是少了个org.apache.velocity.tools.view.tools.LinkTool的配置呀。不然$!link.getContextPath()是为空的。

**Comment by Bosn** [comment]
@Maktub714 额，因为是根目录，所以ContextPath就是空的吧，反之，如果访问http://domain.com/RAP的话，contextPath应该是"/RAP"

**Comment by Maktub714** [comment]
@Bosn  嗯。

**Comment by qixiantong** [comment]
是在http://thx.github.io/RAP/注册吧？我找不到注册的入口啊，wiki上也没说明，可否告知注册的入口？谢谢。

**Comment by zj-chongzi** [comment]
11.5发现个小BUG

array<Object>对象生通过|20的方式生成20条数据，在接口控制台里面正常，但是将控制台生成的连接放到浏览器后就没效果了，而且字段变成了list|20了，希望能解决，拜谢！！

**Comment by Bosn** [comment]
@zj-chongzi 去wiki用户手册，搜一下关键字mockjs。

另外理解一下mockjs模板和最终mock数据的关系，这些在视频教程啊，用户手册里都有写。

**Comment by Sirormy** [comment]
bug 是在这里提吗?
是11.5 里的，自己按源码搭建的本地服务的，登录的时候发现 `StringUtils.getDoubleMD5` 方法的返回值是31位的，正常应该是32位才是，中间少了一位，其他都对

这是我对 `123123` 字符串测试的结果

StringUtils.getDoubleMD5 结果
63ee451939ed58ef3c4b6f0109d1fd0

站长工具加密2次:
63ee451939ed58`0`ef3c4b6f0109d1fd0

貌似中间少了一个零，是有意为之还是... 鄙人驽钝，请@Bosn 老师赐教

**Comment by Bosn** [comment]
@Sirormy 不是有意为之的，但这里目的是为了加密密码，使用非标准MD5加密，只要两次加密后结果一致就可以了。

从加密的意义上来说，这里不一样反而增加了破解难度。考虑到旧密码的兼容。。。。这块儿也并不好修改了。所以就这样吧，哈哈哈哈哈哈

**Comment by skyuning** [comment]
pageTester页面，如果是Post接口，现在也是用Get方式请求的，希望增加Post请求方式

**Comment by skyuning** [comment]
而且点击一次MockJS数据，为什么会发两次请求

**Comment by Bosn** [comment]
@skyuning 发两次请求是因为第二次请求数据，是为了检查格式是否符合API文档的要求。如果你根路径写的别的server，它第二次请求RAP的mock api就是为了验证别的server返回的数据对不对。

pageTester后续会有大的更新，敬请期待。目前功能比较简单，校验服务器接口这个功能建议用RAP插件。

**Comment by skyuning** [comment]
好，多谢，非常期待，非常赞的项目

**Comment by codering** [comment]
@Bosn promise 支持了吗？
